[package]
name = "fighting_game"
version = "0.1.0"
authors = ["Corey Lehman <coreylehman@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.111.0"
find_folder = "*"
gfx_device_gl = "0.16.2"